ALTER TABLE "BOARD" DROP CONSTRAINT IF EXISTS "BOARD_fk0";

ALTER TABLE "BOARD" DROP CONSTRAINT IF EXISTS "BOARD_fk1";

ALTER TABLE "BOARD_LAYOUT" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_fk0";

ALTER TABLE "BOARD_PAGE" DROP CONSTRAINT IF EXISTS "BOARD_PAGE_fk0";

ALTER TABLE "BOARD_PAGE" DROP CONSTRAINT IF EXISTS "BOARD_PAGE_fk1";

ALTER TABLE "BOARD_PAGE" DROP CONSTRAINT IF EXISTS "BOARD_PAGE_fk2";

ALTER TABLE "WIDGET" DROP CONSTRAINT IF EXISTS "WIDGET_fk0";

ALTER TABLE "WIDGET" DROP CONSTRAINT IF EXISTS "WIDGET_fk1";

ALTER TABLE "WIDGET" DROP CONSTRAINT IF EXISTS "WIDGET_fk2";

ALTER TABLE "SELECTOR" DROP CONSTRAINT IF EXISTS "SELECTOR_fk0";

ALTER TABLE "SELECTOR" DROP CONSTRAINT IF EXISTS "SELECTOR_fk1";

ALTER TABLE "WIDGET_SELECTOR" DROP CONSTRAINT IF EXISTS "WIDGET_SELECTOR_fk0";

ALTER TABLE "WIDGET_SELECTOR" DROP CONSTRAINT IF EXISTS "WIDGET_SELECTOR_fk1";

ALTER TABLE "BOARD_LAYOUT_WIDGET" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_WIDGET_fk0";

ALTER TABLE "BOARD_LAYOUT_WIDGET" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_WIDGET_fk1";

ALTER TABLE "BOARD_LAYOUT_WIDGET" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_WIDGET_fk2";

ALTER TABLE "BOARD_LAYOUT_SELECTOR" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_SELECTOR_fk0";

ALTER TABLE "BOARD_LAYOUT_SELECTOR" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_SELECTOR_fk1";

ALTER TABLE "BOARD_LAYOUT_SELECTOR" DROP CONSTRAINT IF EXISTS "BOARD_LAYOUT_SELECTOR_fk2";

DROP TABLE IF EXISTS "BOARD";

DROP TABLE IF EXISTS "BOARD_LAYOUT";

DROP TABLE IF EXISTS "BOARD_PAGE";

DROP TABLE IF EXISTS "PUBLIC_INFO";

DROP TABLE IF EXISTS "CONFIGURATION";

DROP TABLE IF EXISTS "WEB_COMPONENT";

DROP TABLE IF EXISTS "WIDGET";

DROP TABLE IF EXISTS "SELECTOR";

DROP TABLE IF EXISTS "WIDGET_SELECTOR";

DROP TABLE IF EXISTS "BOARD_LAYOUT_WIDGET";

DROP TABLE IF EXISTS "BOARD_LAYOUT_SELECTOR";

